Repository Cazoo-uk/terraform-provider-aws, pull requests merged in 2021-01, with the labels that each got.

#1 Allows EventBus Rule/Target event_bus_name to accept ARN
  aws/resource_aws_cloudwatch_event_rule.go
  aws/resource_aws_cloudwatch_event_target.go
  aws/validators.go
  aws/validators_test.go
Labels: needs-triage, size/M

#2 F event bus resource policy
  aws/provider.go
  aws/resource_aws_cloudwatch_event_bus_policy.go
  aws/resource_aws_cloudwatch_event_bus_policy_test.go
  website/docs/r/cloudwatch_event_bus_policy.html.markdown
Labels: needs-triage, size/L

#4 Allows Rule eventBuName to be an ARN
  aws/internal/service/cloudwatchevents/id.go
Labels: needs-triage, size/XS

#3 Allows Rule eventBuName to be an ARN
  aws/internal/service/cloudwatchevents/id.go
Labels: needs-triage, size/XS
